name: Build RecoverX APK
on:
  workflow_dispatch:
  push:
    branches: [ main, master ]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: subosito/flutter-action@v2
        with:
          channel: 'stable'
          flutter-version: '3.22.0'
      - run: rm -rf android ios lib test .metadata .dart_tool pubspec.* || true
      - run: flutter create --org com.recoverx .
      - run: bash scripts/setup_project.sh
      - run: flutter pub get
      - run: flutter build apk --release
      - uses: actions/upload-artifact@v4
        with:
          name: recoverx-apk
          path: build/app/outputs/flutter-apk/app-release.apk
